---
name: mesos-deployment
director_uuid: <%= '<director-uuid>' %>

releases:
- name: mesos
  version: latest
- name: docker
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: zookeeper
  azs: [z1, z2, z3]
  instances: 3
  jobs:
  - name: zookeeper
    release: mesos
  stemcell: default
  vm_type: medium
  persistent_disk_type: medium
  networks:
  - name: private
- name: mesos-master
  azs: [z1, z2, z3]
  instances: 3
  jobs:
  - name: mesos-master
    release: mesos
  stemcell: default
  vm_type: medium
  networks:
  - name: private
  properties:
    mesos:
      master:
        quorum: 2
        authenticate_agents: true
        authenticate_frameworks: true
- name: mesos-agent
  azs: [z1, z2, z3]
  instances: 3
  jobs:
  - name: docker
    release: mesos
  - name: mesos-agent
    release: mesos
  stemcell: default
  vm_type: medium
  networks:
  - name: private
- name: marathon
  azs: [z1, z2, z3]
  instances: 3
  jobs:
  - name: marathon
    release: mesos
  stemcell: default
  vm_type: medium
  networks:
  - name: private

properties:
  mesos:
    principal: "principal"
    secret: "secret"

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
