releases:
- name: toolbelt
  version: 3.2.10

addons:
- name: toolbelt
  jobs:
  - name: toolbelt
    release: toolbelt
- name: toolbelt-quick
  jobs:
  - name: toolbelt-quick
    release: toolbelt
  # - name: toolbelt-jq
  #   release: toolbelt
